# -*- coding: utf-8 -*-
"""identacao_blocos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

def sacar(valor):
  saldo = 500

  if saldo >= valor:
    print("Valor sacado!")
    print("Retire o seu dinheiro na boca do caixa.")

  print("Obrigado por ser nosso cliente, tenha um bom dia!")

def depositar(valor):
  saldo = 500
  saldo += valor

sacar(3002)