# -*- coding: utf-8 -*-
"""estrutura_while_else

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

opcao = -1

while opcao != 0:
  opcao = int(input("[1] Sacar \n[2] Extrato \n[0] Sair \n: "))

  if opcao == 1:
    print("Sacando...")
  elif opcao == 2:
    print("Exibindo o extrato...")
else:
  print("Obrigado por usar nosso sitema bancário, até logo!")