# -*- coding: utf-8 -*-
"""estrutura_range_for

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

for numero in range(0, 51, 5):
  print(numero, end=" ")