# -*- coding: utf-8 -*-
"""convertendo_tipos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

#Convertendo Inteiros
print(int(1.5))
print(int("10"))

#Convertendo Floats
print(float("10.10"))
print(float(100))

#Convertendo String
print(str(10.10))

#Convertendo Divisão
print(100 / 2)
print(100 // 2)