# -*- coding: utf-8 -*-
"""operadores_associacao

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

frutas = ["limão","uva"]
curso = "Curso de Python"

print("laranja" in frutas)

print("limao" not in frutas)

print("Python" in curso)

