# -*- coding: utf-8 -*-
"""operadores_identidade

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

saldo = 1000
limite = 1000

print(saldo is limite)

print(saldo is not limite)

