# -*- coding: utf-8 -*-
"""string_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

nome = "guilherme"

print(nome.upper())
print(nome.lower())
print(nome.title())

texto = " Olá mundo!   "

print(texto)
print(texto.strip())
print(texto.rstrip())
print(texto.lstrip())

menu = "Python"

print(menu.center(14, "#"))
print("-".join(menu))