# -*- coding: utf-8 -*-
"""string_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

nome = "Kauã"
idade = 19
profissao = "Cientista de Dados"
linguagem = "Python"

print("Nome: %s Idade: %d" % (nome, idade))
print("Nome: {} Idade: {}".format(nome, idade))
print("Nome: {0} Idade: {1}".format(nome, idade)) #Exibindo com indice de posição
print("Nome: {nome} Idade: {idade}".format(nome=nome, idade=idade))