# -*- coding: utf-8 -*-
"""variáveis_constanstes.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

nome = "Guilherme"
idade = 28

nome, idade = "Giovanna", 27

print(nome, idade)

limite_saque_diario = 1000

BRAZILIAN_STATES = ["SP","RJ", "SC", "RS"]

print(BRAZILIAN_STATES)