# -*- coding: utf-8 -*-
"""operadores_atribuicao

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

saldo = 500
print(saldo)

saldo = 200
print(saldo)

saldo += 10
print(saldo)

saldo -= 5
print(saldo)

saldo /= 2
print(saldo)

saldo //= 2
print(saldo)

saldo *= 10
print(saldo)

saldo %= 4
print(saldo)

saldo **= 2
print(saldo)