# -*- coding: utf-8 -*-
"""print_input

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJh_j1fknPHGLrfqVmSPieaTVekOvEUk
"""

nome = input("Informe o seu nome: ")
idade = input("Informe sua idade: ")

print(nome, idade)
print(nome, idade, end="... \n")
print(nome, idade, sep="#")
print(nome, idade, sep="#", end="... \n")